### ISSUE TITLE
Nothing Shown 

### ISSUE THREAD

**Issue by salmanfarisvp** [JackBradach/Curie_the_HoG#1]
Nice idea , am very interested 
I used the Arduino code for Arduino 101, upoload was Done without error , but nothing happen after that.
i searched for ble device nothing found

**Comment by jackbradach** [comment]
I've been neglecting this project; new job, sorry. :-)

I'll try to find some time this weekend to clean up some code I've been lazy about committing.  I think my local has the bluetooth code "working," but not doing much more than connecting.  For what it's worth, it's based off the HID over GATT examples from the Zephyr tree.  If you have tried that and were having trouble getting tools like Nordic nRF Connect or your operating system to see the test data on an HID, there's a BLE quirk you might be interested in knowing.

The bluetooth stack of most operating systems will claim any HID they see for themselves, circumventing the ability of the development tools from being able to talk to them.  The symptom is something like nRF Connect sees the device but when you try to read the HID characteristics, it never responds.  Once you get to that point, you can talk to it the same way you could a mouse or keyboard.

**Comment by salmanfarisvp** [comment]
ok , thanks . i'll try my best <3
